name: 'Set and export environment variable in powershell'
description: 'Set and export environment variable using powershell to be available for the steps that follow.'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  name:
    description: 'name of the variable'
    required: true
  value:
    description: 'value of the variable'
    required: true
runs:
  using: "composite"
  steps:
    - name: export environment variable
      run: echo "${{ inputs.name }}=${{ inputs.value }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell
